"""empty message

Revision ID: 482df3b99148
Revises: 37b364468e41
Create Date: 2017-11-03 00:13:00.673126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482df3b99148'
down_revision = '37b364468e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_email'), table_name='User')
    # ### end Alembic commands ###
